# Generated by Django 3.2.6 on 2021-10-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilaya',
            name='mat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matricule'),
        ),
    ]
