# Generated by Django 3.2.6 on 2021-08-31 08:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atributes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category')),
            ],
            options={
                'verbose_name': 'Sous Catégorie',
                'verbose_name_plural': '3. Sous Catégorie',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='Sujet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Formulaire de contact',
                'verbose_name_plural': 'Formulaire de contact',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Déscription du produit')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancien prix')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('new', models.BooleanField(default=True, verbose_name='Nouveau')),
                ('top', models.BooleanField(default=True, verbose_name='Meilleur vente')),
                ('status', models.CharField(blank=True, choices=[('N', 'Nouveau'), ('R', 'Rupture'), ('P', 'Promotion')], default='N', max_length=1, null=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Sous Catégorie')),
                ('tag', models.ManyToManyField(blank=True, to='atributes.Tag')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': '4. Produits',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PhotoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/produits')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.product')),
            ],
        ),
    ]
