# Generated by Django 3.2.6 on 2021-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210901_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributes',
            options={'verbose_name': 'Produits Specification', 'verbose_name_plural': 'Produits Specifications'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': '- Produits Type', 'verbose_name_plural': '- Produits Types'},
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(help_text='Required', max_length=255, unique=True, verbose_name='Type'),
        ),
    ]
