# Generated by Django 3.2.6 on 2021-09-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name': 'Produit Details', 'verbose_name_plural': 'Produit Details'},
        ),
        migrations.RenameField(
            model_name='photoproduct',
            old_name='photo',
            new_name='fichier',
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/produits')),
                ('name', models.CharField(max_length=25, verbose_name='Nom du document')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.product')),
            ],
        ),
    ]
