# Generated by Django 3.2.6 on 2021-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence'),
        ),
    ]
