# Generated by Django 3.2.6 on 2021-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_productdetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='file',
            field=models.FileField(upload_to='images/produits'),
        ),
    ]
