# Generated by Django 3.2.6 on 2021-09-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributes',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producttype'),
        ),
    ]
