# Generated by Django 3.2.6 on 2021-09-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_atributes_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributes',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/produits'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories'),
        ),
    ]
