# Generated by Django 3.2.6 on 2021-09-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210904_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('id',), 'verbose_name': '- Marque', 'verbose_name_plural': '- Marque'},
        ),
    ]
