# Generated by Django 3.2.6 on 2021-09-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_brand_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
