# Generated by Django 3.2.6 on 2021-09-13 09:23

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('id',), 'verbose_name': '- Marque', 'verbose_name_plural': '- Marques'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Catégorie'),
        ),
    ]
