# Generated by Django 3.2.6 on 2021-09-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Atribut')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributes', to='core.producttype')),
            ],
            options={
                'verbose_name': 'Produits Specification',
                'verbose_name_plural': 'Produits Specifications',
            },
        ),
        migrations.AlterField(
            model_name='atributesvalue',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.atribute'),
        ),
        migrations.DeleteModel(
            name='Atributes',
        ),
    ]
