# Generated by Django 3.2.6 on 2021-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210921_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Nouveau'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('R', 'Rupture'), ('P', 'Promotion')], default='N', max_length=1, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top',
            field=models.BooleanField(default=False, verbose_name='Meilleur vente'),
        ),
    ]
