# Generated by Django 3.2.6 on 2021-10-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20211006_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Stock initial'),
        ),
    ]
