# Generated by Django 3.2.6 on 2021-10-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=200, unique=True, verbose_name='Référence'),
        ),
    ]
