# Generated by Django 3.2.6 on 2021-08-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '2. Banner'},
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': '1. Infomation'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': '3. Photos Acceuil'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(upload_to=None, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='photo',
            field=models.ImageField(upload_to=None),
        ),
    ]
