# Generated by Django 3.2.6 on 2021-08-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20210831_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': '1. Infomation', 'verbose_name_plural': '1. Infomations'},
        ),
    ]
