# Generated by Django 3.2.6 on 2021-09-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20210902_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': '5. Accomplissement', 'verbose_name_plural': '5. Accomplissement'},
        ),
        migrations.AlterModelOptions(
            name='largebanner',
            options={'verbose_name': "3. Grand Banner bas de page d'accueil", 'verbose_name_plural': "3. Grand Banner bas de d'accueil"},
        ),
    ]
