# Generated by Django 3.2.6 on 2021-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20210902_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(max_length=150, verbose_name="nom de l'acomplissement"),
        ),
    ]
