# Generated by Django 3.2.6 on 2021-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_counter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(upload_to='slides/', verbose_name='Slide 870 X 475 px'),
        ),
        migrations.AlterField(
            model_name='business',
            name='about_photo',
            field=models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Photo A propos 440 X 275 px'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='icon',
            field=models.ImageField(upload_to='icons/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='largebanner',
            name='photo',
            field=models.ImageField(upload_to='slides/', verbose_name='Slide 870 X 475 px'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='photo',
            field=models.ImageField(upload_to='slides/', verbose_name='photo 370 X 225 px'),
        ),
    ]
