# Generated by Django 3.2.6 on 2021-09-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20210903_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slide',
            new_name='ThreePhotos',
        ),
    ]
