# Generated by Django 3.2.6 on 2021-09-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20210903_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dualbanner',
            options={'verbose_name': '3. Petits Banners en duo', 'verbose_name_plural': '3. Petits Banners en duo'},
        ),
    ]
