# Generated by Django 3.2.6 on 2021-09-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_dualbanner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dualbanner',
            name='photo',
            field=models.ImageField(upload_to='slides/', verbose_name='photo 570 X 200 px'),
        ),
        migrations.AlterField(
            model_name='largebanner',
            name='photo',
            field=models.ImageField(upload_to='slides/', verbose_name='Slide 1170 X 400 px'),
        ),
    ]
