# Generated by Django 3.2.6 on 2021-09-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20210903_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AddField(
            model_name='dualbanner',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AddField(
            model_name='slide',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
    ]
