# Generated by Django 3.2.6 on 2021-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20210904_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='before',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='avant le chiffre'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='number',
            field=models.IntegerField(verbose_name='chiffre'),
        ),
    ]
