# Generated by Django 3.2.6 on 2021-09-05 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_partner_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisationphotos',
            name='realisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.realisation', verbose_name='Projet / Réalisation'),
            preserve_default=False,
        ),
    ]
