# Generated by Django 3.2.6 on 2021-09-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_realisationphotos_realisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='contact_message',
            field=models.TextField(blank=True, null=True, verbose_name='Contact message'),
        ),
        migrations.AddField(
            model_name='business',
            name='email2',
            field=models.EmailField(blank=True, max_length=50, verbose_name="2eme email de l'entreprise"),
        ),
        migrations.AddField(
            model_name='business',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, verbose_name="2eme numéro de téléphone de l'entreprise"),
        ),
    ]
