# Generated by Django 3.2.6 on 2021-09-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_auto_20210911_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_maps',
            field=models.TextField(blank=True, null=True, verbose_name='iframe google maps'),
        ),
    ]
