# Generated by Django 3.2.6 on 2021-09-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_business_google_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="nom de l'acomplissement")),
                ('sub_title', models.CharField(max_length=150, verbose_name="nom de l'acomplissement")),
                ('icon', models.ImageField(upload_to='icons/', verbose_name='icon')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': '7. Service Clients',
                'verbose_name_plural': '7. Services Clients',
            },
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': '6. Accomplissement', 'verbose_name_plural': '6. Accomplissement'},
        ),
        migrations.AlterModelOptions(
            name='dualbanner',
            options={'verbose_name': '4. Petits Banners en duo', 'verbose_name_plural': '4. Petits Banners en duo'},
        ),
        migrations.AlterModelOptions(
            name='largebanner',
            options={'verbose_name': "5. Grand Banner bas de page d'accueil", 'verbose_name_plural': "5. Grand Banner bas de d'accueil"},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': '10. Nos Partenaires', 'verbose_name_plural': '10. Nos Partenaires'},
        ),
        migrations.AlterModelOptions(
            name='realisation',
            options={'verbose_name': '8. Nos Projets', 'verbose_name_plural': '8. Nos Projets'},
        ),
        migrations.AlterModelOptions(
            name='realisationphotos',
            options={'verbose_name': '9. Photos de Nos Projets', 'verbose_name_plural': '9. Photos de Nos Projets'},
        ),
    ]
