# Generated by Django 3.2.6 on 2021-09-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20210912_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='icon',
            field=models.ImageField(upload_to='icons/', verbose_name='icon 67 X 57 px '),
        ),
    ]
