# Generated by Django 3.2.6 on 2021-09-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_alter_clientservice_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': '9. Nos Partenaires', 'verbose_name_plural': '9. Nos Partenaires'},
        ),
    ]
