# Generated by Django 3.2.6 on 2021-10-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_alter_partner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='icon'),
        ),
    ]
