# Generated by Django 3.2.6 on 2021-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_alter_realisationphotos_realisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisationphotos',
            name='image',
            field=models.ImageField(upload_to='images/projets/', verbose_name='image'),
        ),
    ]
