# Generated by Django 3.2.6 on 2021-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_alter_realisationphotos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Déscription du produit'),
        ),
    ]
