# Generated by Django 3.2.6 on 2021-10-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_alter_realisation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='siteweb',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Lien'),
        ),
    ]
