# Generated by Django 3.2.6 on 2021-09-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atributes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cheveux',
        ),
        migrations.DeleteModel(
            name='Parfum',
        ),
    ]
