# Generated by Django 3.2.6 on 2021-09-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='campany',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Entrprise'),
        ),
    ]
